import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { tokensToCss } from "../src/design/tokens/toCss.ts";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(ROOT, "src/design/tokens.generated.css");

fs.writeFileSync(
	OUTPUT,
	`/* Generated by scripts/generate-design-css.ts. Do not edit by hand. */\n${tokensToCss()}`,
	"utf8",
);

console.info(`Wrote ${OUTPUT}`);
